version: "3.9"
services:
  db:
    image: postgres
    container_name: "db"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - pg-bikes-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  
  server:
    image: bikes/server
    build: ./bikes_backend
    restart: always
    volumes:
      - ./bikes_backend:/app
      - ./data:/data
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - WATCHFILES_FORCE_POLLING=true

  client:
    image: bikes/client
    build: ./bikes_frontend
    volumes:
        - './bikes_frontend:/app'
        - '/app/node_modules'
    restart: always
    ports:
      - "3000:3000"

volumes:
  pg-bikes-data:
    external: true